#!/usr/bin/env python

def options(opt):
    pass

def configure(conf):
    pass

def build(bld):
    #Thread is needed by OSC/Endpoint
    #File is for nsmd lockfiles
    bld.stlib(
        source = '''
OSC/Endpoint.C
Thread.C
debug.C
file.C
''',
        includes = '.',
        export_incdirs = [ '.', 'nonlib'],
        uselib = 'LIBLO JACK PTHREAD',
        target = 'nonlib')
