#!/bin/sh

# Copyright (C) 2008 Jonathan Moore Liles                                     #
#                                                                             #
# This program is free software; you can redistribute it and/or modify it     #
# under the terms of the GNU General Public License as published by the       #
# Free Software Foundation; either version 2 of the License, or (at your      #
# option) any later version.                                                  #
#                                                                             #
# This program is distributed in the hope that it will be useful, but WITHOUT #
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or       #
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for   #
# more details.                                                               #
#                                                                             #
# You should have received a copy of the GNU General Public License along     #
# with This program; see the file COPYING.  If not,write to the Free Software #
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.  #

#####
## Simple script to scan source files for GPL headers.
##

R=0

for i in "$@"
do
    HEAD="`head $i`"

    S=

    if echo "$HEAD" | grep -q Copyright
    then
        if echo "$HEAD" | grep -q 'GNU General Public License'
        then
            S="GPL"

            if echo "$HEAD" | grep -q 'version 2'
            then
                S="${S}v2"
            elif echo "$HEAD" | grep -q 'version 3'
            then
                S="${S}v3"
            fi

            if echo "$HEAD" | grep -q 'any later version'
            then
                S="${S}+"
            fi
        else
            S="Not GPL!"
            R=255
        fi

    else
        S="No Copyright!"
        R=255
    fi

    printf "%-60s %s\n" "${i}:" "$S"
done


exit $R